### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by renkun-ken** [Ikuyadeu/vscode-R#265]
The extension does not build:

```
$ vsce package
Executing prepublish script 'npm run vscode:prepublish'...
 ERROR  Command failed: npm run vscode:prepublish
/Users/ken/Workspaces/github/vscode-R/webpack.config.js:3
import { resolve as _resolve } from 'path';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at new Script (vm.js:99:7)
    at NativeCompileCache._moduleCompile (/Users/ken/Workspaces/github/vscode-R/node_modules/_v8-compile-cache@2.0.3@v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/Users/ken/Workspaces/github/vscode-R/node_modules/_v8-compile-cache@2.0.3@v8-compile-cache/v8-compile-cache.js:186:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (/Users/ken/Workspaces/github/vscode-R/node_modules/_v8-compile-cache@2.0.3@v8-compile-cache/v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (/Users/ken/Workspaces/github/vscode-R/node_modules/_webpack-cli@3.3.11@webpack-cli/bin/utils/convert-argv.js:114:13)
    at requireConfig (/Users/ken/Workspaces/github/vscode-R/node_modules/_webpack-cli@3.3.11@webpack-cli/bin/utils/convert-argv.js:116:6)
    at /Users/ken/Workspaces/github/vscode-R/node_modules/_webpack-cli@3.3.11@webpack-cli/bin/utils/convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (/Users/ken/Workspaces/github/vscode-R/node_modules/_webpack-cli@3.3.11@webpack-cli/bin/utils/convert-argv.js:121:15)
    at /Users/ken/Workspaces/github/vscode-R/node_modules/_webpack-cli@3.3.11@webpack-cli/bin/cli.js:71:45
    at Object.parse (/Users/ken/Workspaces/github/vscode-R/node_modules/_yargs@13.2.4@yargs/yargs.js:567:18)
    at /Users/ken/Workspaces/github/vscode-R/node_modules/_webpack-cli@3.3.11@webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/Users/ken/Workspaces/github/vscode-R/node_modules/_webpack-cli@3.3.11@webpack-cli/bin/cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/ken/Workspaces/github/vscode-R/node_modules/_webpack@4.42.1@webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! r@1.2.7 vscode:prepublish: `webpack --mode production`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the r@1.2.7 vscode:prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

```
$ node --version
v13.11.0
```

This error also occurs in CI too.

**Comment by Ikuyadeu** [comment]
Thank you for notifying me.  I fixed now.
It is occurred due to https://github.com/Ikuyadeu/vscode-R/commit/dcd5f909e8be9d945978aa42888331d190abf384
