### ISSUE TITLE
plots generated by httpgd do not appear automatically

### ISSUE THREAD

**Issue by jooyoungseo** [Ikuyadeu/vscode-R#671]
I was wondering if there would be any convenient way to find generated plot outputs with `httpgd`.

Nothing happens after creating a plot. I have to manually open a browser and go to the url specified within `httpgd::hgd_browse()`.

The following includes my options in `Rprofile`:

``` r
options(vsc.rstudioapi = TRUE)
options(vsc.use_httpgd = TRUE)
```

Of course, `httpgd` has been installed.

**Comment by renkun-ken** [comment]
When `vsc.use_httpgd = TRUE` is used, any plot update should reveal the plot viewer automatically.

Does it work if you execute vscode command "R Plot: Show viewers"?

@ManuelHentschel Any idea on this?

**Comment by jooyoungseo** [comment]
So weird, this issue doesn't occur with v1.6.8. I have found that "R: Luanch RStudio Addin" doesn't work, either with v2.0.0.

In sum, the newest version v2.0.0 seems to have some issues on Windows.

**Comment by renkun-ken** [comment]
The major change from v1.6.8 to v2.0.0 is made in #626. Everything works well under Ubuntu and macOS. @ElianHugh It looks like you are using Windows. Could you reproduce the problem here?

**Comment by ElianHugh** [comment]
I'm on Linux until tomorrow night, but haven't experienced any of the problems outlined here. I don't see anything from the 2.0 release that would cause this to happen, particularly when the rstudioapi was not touched at all

**Comment by renkun-ken** [comment]
@jooyoungseo Could you go to "Help -> Toggle Developer Tools" and choose "Console" tab when you start an R session. If the extension is successfully activated and the session attached, the following log is expected:

```
[Extension Host] Start language server for file:///home/renkun/Workspaces/testR/httpgd.R
console.ts:137 [Extension Host] R binary: /usr/bin/R
console.ts:137 [Extension Host] LANG: en_US.UTF-8
console.ts:137 [Extension Host] R process connected
console.ts:137 [Extension Host] activating extension
console.ts:137 [Extension Host] starting language server
console.ts:137 [Extension Host] [LiveSessionListener] started
console.ts:137 [Extension Host] Initialize session watcher
console.ts:137 [Extension Host] [deploySessionWatcher] extensionPath: /home/renkun/.vscode/extensions/ikuyadeu.r-2.0.0
console.ts:137 [Extension Host] [deploySessionWatcher] watcherDir: /home/renkun/.vscode-R
console.ts:137 [Extension Host] Create sessionStatusBarItem
console.ts:137 [Extension Host] [startRequestWatcher] Starting
console.ts:137 [Extension Host] [startRequestWatcher] Done
```

**Comment by jooyoungseo** [comment]
@renkun-ken, thanks for your help! The following includes my console log:

```
abstractExtensionService.ts:911 Couldn't find message for key config.runtime.builtin.table.
abstractExtensionService.ts:911 Couldn't find message for key config.runtime.builtin.utf8.
console.ts:137 [Extension Host] Start language server for file:///c:/test/test.R
console.ts:137 [Extension Host] R binary: C:\Program Files\R\R-4.1.0\bin\x64\R.exe
console.ts:137 [Extension Host] LANG: en_US.UTF-8
localProcessExtensionHost.ts:272 Extension Host
localProcessExtensionHost.ts:273 '"c:\Users\sjysk\.vscode\extensions\kiteco.kite-0.147.0\dist\read-key.bat"' is not recognized as an internal or external command,
operable program or batch file.
console.ts:137 [Extension Host] R process connected
mainThreadExtensionService.ts:95 Activating extension 'ms-vsliveshare.vsliveshare' failed: Agent terminated with exit code: 0 and signal null: Error:
  An assembly specified in the application dependencies manifest (Microsoft.NETCore.App.deps.json) was not found:
    package: 'runtime.win-x86.Microsoft.NETCore.App', version: '3.1.14-servicing.21165.2'
    path: 'runtimes/win-x86/lib/netcoreapp3.1/System.Net.NameResolution.dll'.
mainThreadExtensionService.ts:95 Cannot activate the 'Live Share Audio' extension because its dependency 'Live Share' failed to activate
mainThreadExtensionService.ts:95 Activating extension 'Ikuyadeu.r' failed: Agent terminated with exit code: 0 and signal null: Error:
  An assembly specified in the application dependencies manifest (Microsoft.NETCore.App.deps.json) was not found:
    package: 'runtime.win-x86.Microsoft.NETCore.App', version: '3.1.14-servicing.21165.2'
    path: 'runtimes/win-x86/lib/netcoreapp3.1/System.Net.NameResolution.dll'.
console.ts:137 [Extension Host] termPath: C:\Program Files\R\R-4.1.0\bin\x64\R.exe
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: Agent terminated with exit code: 0 and signal null: Error:
  An assembly specified in the application dependencies manifest (Microsoft.NETCore.App.deps.json) was not found:
    package: 'runtime.win-x86.Microsoft.NETCore.App', version: '3.1.14-servicing.21165.2'
    path: 'runtimes/win-x86/lib/netcoreapp3.1/System.Net.NameResolution.dll'
console.ts:137 [Extension Host] stack trace: Error: Agent terminated with exit code: 0 and signal null: Error:
  An assembly specified in the application dependencies manifest (Microsoft.NETCore.App.deps.json) was not found:
    package: 'runtime.win-x86.Microsoft.NETCore.App', version: '3.1.14-servicing.21165.2'
    path: 'runtimes/win-x86/lib/netcoreapp3.1/System.Net.NameResolution.dll'
	at ChildProcess.<anonymous> (c:\Users\sjysk\.vscode\extensions\ms-vsliveshare.vsliveshare-1.0.4419\out\prod\extension-prod.js:194642:32)
	at ChildProcess.emit (events.js:327:22)
	at maybeClose (internal/child_process.js:1048:16)
	at Socket.<anonymous> (internal/child_process.js:439:11)
	at Socket.emit (events.js:315:20)
	at Pipe.<anonymous> (net.js:673:12)
mainThreadExtensionService.ts:63 [[object Object]]Agent terminated with exit code: 0 and signal null: Error:
  An assembly specified in the application dependencies manifest (Microsoft.NETCore.App.deps.json) was not found:
    package: 'runtime.win-x86.Microsoft.NETCore.App', version: '3.1.14-servicing.21165.2'
    path: 'runtimes/win-x86/lib/netcoreapp3.1/System.Net.NameResolution.dll'
mainThreadExtensionService.ts:64 Error: Agent terminated with exit code: 0 and signal null: Error:
  An assembly specified in the application dependencies manifest (Microsoft.NETCore.App.deps.json) was not found:
    package: 'runtime.win-x86.Microsoft.NETCore.App', version: '3.1.14-servicing.21165.2'
    path: 'runtimes/win-x86/lib/netcoreapp3.1/System.Net.NameResolution.dll'
	at ChildProcess.<anonymous> (c:\Users\sjysk\.vscode\extensions\ms-vsliveshare.vsliveshare-1.0.4419\out\prod\extension-prod.js:194642:32)
	at ChildProcess.emit (events.js:327:22)
	at maybeClose (internal/child_process.js:1048:16)
	at Socket.<anonymous> (internal/child_process.js:439:11)
	at Socket.emit (events.js:315:20)
	at Pipe.<anonymous> (net.js:673:12)
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: ENOENT: no such file or directory, unlink 'c:\Users\sjysk\.vscode\extensions\ms-vsliveshare.vsliveshare-1.0.4419\cascade.json'
console.ts:137 [Extension Host] stack trace: Error: ENOENT: no such file or directory, unlink 'c:\Users\sjysk\.vscode\extensions\ms-vsliveshare.vsliveshare-1.0.4419\cascade.json'
log.ts:296   ERR ENOENT: no such file or directory, unlink 'c:\Users\sjysk\.vscode\extensions\ms-vsliveshare.vsliveshare-1.0.4419\cascade.json': Error: ENOENT: no such file or directory, unlink 'c:\Users\sjysk\.vscode\extensions\ms-vsliveshare.vsliveshare-1.0.4419\cascade.json'
```

**Comment by ElianHugh** [comment]
Thanks for posting the logs! It looks like an error with the Live Share extension install as per https://github.com/MicrosoftDocs/live-share/issues/1904. Would you be able to delete the Live Share extension from your `c:\Users\sjysk\.vscode\extensions\` folder and then reinstall the Live Share extension?

**Comment by ManuelHentschel** [comment]
> 
> The major change from v1.6.8 to v2.0.0 is made in #626. Everything works well under Ubuntu and macOS. @ElianHugh It looks like you are using Windows. Could you reproduce the problem here?

I can't reproduce the issue on windows with v2.0.0, so I'd guess it's an issue with live-share as @ElianHugh suggested.

**Comment by renkun-ken** [comment]
Looks like the incorrect installation of live share prevents vscode-R from activating, so that the session is never attached.

**Comment by ElianHugh** [comment]
it might be worth catching errors in the initial attempt to access the Live Share API, so we can provide a more user friendly error message

**Comment by jooyoungseo** [comment]
Yes, reinstalling the 'ms-vsliveshare.vsliveshare' has resolved this issue. Thank you very much!
